build: add prettier instead of tslint
dreamstechnology/dreams-web-sdk pull request #22
Opened 2021-11-15 15:18 UTC by bolmaster2

With the argument that tslint is deprecated and eslint should be used instead for linting. 

...and then add prettier for formatting which IMO is the industry standard _and_ very handy to not care about code formatting and it's taking the decision for us

2021-11-15 16:09 UTC, loffek requested changes
Sounds good to me!

2021-11-15 16:09 UTC, loffek commented on .github/workflows/ci.yml
> +          persist-credentials: false
This is only needed for commit lint to work, so no need to add it here (but see next comment)

2021-11-15 16:09 UTC, loffek commented on .github/workflows/ci.yml
> +        run: npm run prettier-check
And remove lines:

https://github.com/getdreams/dreams-web-sdk/pull/22/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR37-R39

https://github.com/getdreams/dreams-web-sdk/pull/22/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR54-R55y

2021-11-16 09:05 UTC, bolmaster2 commented on .github/workflows/ci.yml
> +        run: npm run prettier-check
I just realized it's not needed in the ci at all, or do it have any purpose here when we run it on pre-commit?

2021-11-19 10:15 UTC, loffek commented on .github/workflows/ci.yml
> +        run: npm run prettier-check
The problem is that it is optional to install lefthook, so we need to *verify* in the CI that everything is formatted correctly:

- pre-commit: run it in write mode
- in CI: run it in verify / check mode

2022-05-11 09:57 UTC, closed without merging

2022-05-11 12:40 UTC, bolmaster2 commented
I restarted fresh in a new PR here instead: https://github.com/dreamstechnology/dreams-web-sdk/pull/31